---
# ERLANG
- name: Erlang key
  apt_key: url=https://packages.erlang-solutions.com/debian/erlang_solutions.asc state=present

#- name: Erlang src
#  apt_repository: repo='deb http://packages.erlang-solutions.com/debian jessie_amd64 contrib' state=absent

- name: Erlang src
  apt_repository: repo='deb http://packages.erlang-solutions.com/debian jessie contrib' state=present

# RABBITMQ
- name: RabbitMQ key
  apt_key: url=https://www.rabbitmq.com/rabbitmq-release-signing-key.asc state=present
               
- name: RabbitMQ src
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

- name: Update apt
  apt: update_cache=yes

- name: Install Erlang+RabbitMQ
  apt: pkg={{ item }} state=latest
  with_items:
    - erlang
    - rabbitmq-server
    - python-pip
    - python-dev
    - python-psycopg2
    - python-lxml

- name: Install Supervisor
  apt: pkg={{ item }} state=latest
  with_items:
    - supervisor

- pip: name=pika
- pip: name=psutil
- pip: name=apns
- pip: name=redis

- name: enable rabbitmq plugins
#  rabbitmq_plugin: names=rabbitmq_management,rabbitmq_tracing,rabbitmq_federation state=enabled
  rabbitmq_plugin: names=rabbitmq_management state=enabled
  notify:
  - restart rabbitmq

- name: add users
  rabbitmq_user: user=lapin password=lapin tags=administrator,lapin vhost=/ configure_priv=.* write_priv=.* read_priv=.* state=present

- name: remove default guest user
  rabbitmq_user: user=guest state=absent

- name: ensure vhost /test is present
  rabbitmq_vhost: name=/test state=present

- name: Create /srv/Logs
  file: path=/srv/Logs state=directory

