# -*- mode: ruby -*-
# vi: set ft=ruby :

# set minimal Vagrant version
Vagrant.require_version ">= 1.5.0"


Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true
  # see https://twitter.com/mitchellh/status/525704126647128064
  config.ssh.insert_key = false

  config.vm.define "basebox" do |basebox|
    basebox.vm.hostname = "basebox"
    basebox.vm.box = "ARTACK/debian-jessie"
    basebox.vm.network "private_network", ip: "172.16.1.2"

    basebox.vm.provision "ansible" do |ansible|
      ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
      ansible.verbose    = "v"
      ansible.playbook   = "basebox.yml"
    end


    # Providers specific section
    basebox.vm.provider "virtualbox" do |v|
      #v.name = "BaseBox" # name in the VirtualBox GUI, used to build the box
      v.gui = false
      v.memory = 1024
      v.customize ["modifyvm", :id, "--cpuexecutioncap", 50]
      v.customize ["modifyvm", :id, "--cpus", "2"]
      v.customize ["modifyvm", :id, "--usb", "off"]
      v.customize ["modifyvm", :id, "--usbehci", "off"]
    end
  end
end
