---
# see .rsync-filter file
- name: Install /srv/Tempr/DB
  synchronize:
    rsync_path="sudo rsync"
    src=/opt/Tempr/DB
    dest=/srv/Tempr/

- name: Destroy Database (DEV only)
  become: true
  become_user: postgres
  command: /srv/Tempr/DB/bin/destroy_database.sh
  #when: tempr_environment == 'development'

- name: Build Database
  become: true
  become_user: postgres
  command: /srv/Tempr/DB/bin/build_database.sh


