- name: Install ufw
  apt: pkg={{ item }} state=latest
  with_items:
    - ufw

#- name: Allow ssh from private network
#  ufw: rule=allow port=22

- debug: msg="ufw_rules is {{ ufw_rules|default('undefined') }}"
  #when: ufw_rules|default(False)

- name: Configure additional UFW rules
  ufw:
    port: "{{ item.port if item.port is defined else '' }}"
    rule: "{{ item.rule if item.rule is defined else 'allow' }}"
    proto: "{{ item.proto if item.proto is defined else 'any' }}"
    to_ip: "{{ item.to_ip if item.to_ip is defined else 'any' }}"
    from_ip: "{{ item.from_ip if item.from_ip is defined else 'any' }}"
  with_items: '{{ ufw_rules }}'
  notify: Reload UFW
  when: ufw_rules|default(False)

- name: Set firewall default policy
  ufw: state=enabled policy=reject
  #ufw: state={{'disabled' if tempr_environment == 'development' else 'enabled'}} policy=reject
