---
- name: .htpasswd
  copy:
    src=htpasswd
    dest=/opt/librenms/html/.htpasswd
    owner=www-data
    group=www-data
    mode=0600


- name: Update .htaccess
  blockinfile:
    dest: /opt/librenms/html/.htaccess
    insertafter: EOF
    marker: "# auth {mark}"
    content: |
      AuthUserFile /opt/librenms/html/.htpasswd
      #AuthGroupFile /dev/null
      AuthName "Stop"
      AuthType Basic
      <limit GET>
      require valid-user
      </limit>
